Enhanced logger w/ winston
sprucelabsai/sprucebot-log pull request #9
Opened 2019-06-10 19:21 UTC by kengoldfarb

Backwards-compatible with log levels and usage. This should be a drop in replacement for existing projects.  However, I've marked this as a **major** release because the log format / output has been adjusted.

* Use spruce eslint config

* Uses [winston](https://github.com/winstonjs/winston) for BE logs

* Changes `useTrace` and `useSourcemaps` to default to false for performance improvements

* Add `asJSON` option to format log output as JSON

* Add ability to pass in custom `formatters` and `transports` to allow full customization of how logs are written

  * This will be integrated into workspace w/ an upcoming PR

* Basic tests of logging functionality (not exhaustive)

* Integrate `debug` module for logger debugging

* README updates

2019-06-10 19:43 UTC, justinhillsjohnson commented
Let's hold on merging this baby until after we've deployed to QA today

2019-06-11 15:30 UTC, corbanb approved these changes
LGTM :shipit:

2019-06-11 15:38 UTC, justinhillsjohnson requested changes
Seems like maybe we have some unrelated changes in this PR. Changes that would be good to have, but shouldn't be done as part of the logger PR. I left a couple of comments but I see other clean-up happening beyond that.

2019-06-11 15:38 UTC, justinhillsjohnson commented on .editorconfig
> +trim_trailing_whitespace = false
Are these updates necessary for the logger? Where do these defaults come from and are they set consistently and/or sanely across all repos?

2019-06-11 15:38 UTC, justinhillsjohnson commented on .vscode/launch.json
> +// 20170402175629
Is this file update related?

2019-06-11 15:47 UTC, justinhillsjohnson approved these changes

2019-06-11 15:48 UTC, merged